### ISSUE TITLE
error while Building an ExecuTorch Android Demo App

### ISSUE THREAD

**Issue by tggmbi** [pytorch/executorch#3463]
following the tutorial here :
https://pytorch.org/executorch/stable/demo-apps-android.html#id3
trying to tun this command :
python -m examples.qualcomm.scripts.deeplab_v3 -b build_android -m SM8450 -s MYSERIALCODE
I am getting this:
`Traceback (most recent call last):
  File "/Users/xxxx/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/xxxx/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/xxxx/executorch/examples/qualcomm/scripts/deeplab_v3.py", line 18, in <module>
    from executorch.examples.qualcomm.scripts.utils import (
ModuleNotFoundError: No module named 'executorch.examples.qualcomm'
`

**Comment by cccclai** [comment]
Thank you for trying it out! Seems like a set up issue, did you follow https://pytorch.org/executorch/0.2/build-run-qualcomm-ai-engine-direct-backend.html to install the required dependancy?

**Comment by byjlw** [comment]
This should be fixed now

**Comment by KarthikL1729** [comment]
Has this been fixed? I ran into the same import error on the viable/strict branch, and the way I got past the import issue was adding a symlink in EXECUTORCH_ROOT/src/executorch/examples that pointed to EXECUTORCH_ROOT/examples/qualcomm. The symlink doesn't exist in the main branch either, so I think the issue is still there?

**Comment by cccclai** [comment]
It should be fixed. When seeing this error, usually it either means either the build.sh (https://github.com/pytorch/executorch/blob/main/backends/qualcomm/scripts/build.sh) didn't run or the environment variable is no set properly (search Qualcomm in [executorch.ai/](https://executorch.ai/))
